import type { Metadata } from "next";
import { Lora, Onest } from "next/font/google";
import "./globals.css";

const loraSans = Lora({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const onestSans = Onest({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${loraSans.variable} ${onestSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
